  epochs: 500000
  batch_size: 64
  spatial_size: 28
  log_freq: 100
  lr_rate: 1e-4
  log_dir: /scratch_net/bmicdl03/jonatank/logs/ddp/vae_pytorch
  path: /srv/beegfs02/scratch/fastmri_challenge/data/brain
